#!/bin/sh
#
# @name Quadrotor + Tailsitter
#
# @type VTOL Quad Tailsitter
#

. ${R}etc/init.d/rc.vtol_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
# PX4_SIM_MODEL=${PX4_SIM_MODEL:=quadtailsitter}

PX4_GZ_MODEL_NAME=${PX4_GZ_MODEL_NAME:=awetailsitter}

param set-default SIM_GZ_EN 1 # Gazebo bridge

param set-default MAV_TYPE 20

param set-default CA_AIRFRAME 4

# param set-default SYS_AUTOSTART	1001

# Motors (Rotors) params
# KM: yaw torque constant
param set-default CA_ROTOR_COUNT 4

param set-default CA_ROTOR0_KM	-0.05
param set-default CA_ROTOR0_PX	0.00
param set-default CA_ROTOR0_PY	-0.80
param set-default CA_ROTOR0_PZ	0.00

param set-default CA_ROTOR1_KM	0.05
param set-default CA_ROTOR1_PX	0.00
param set-default CA_ROTOR1_PY	-0.30
param set-default CA_ROTOR1_PZ	0.00

param set-default CA_ROTOR2_KM	-0.05
param set-default CA_ROTOR2_PX	0.00
param set-default CA_ROTOR2_PY	0.30
param set-default CA_ROTOR2_PZ	0.00

param set-default CA_ROTOR3_KM	0.05
param set-default CA_ROTOR3_PX	0.00
param set-default CA_ROTOR3_PY	0.80
param set-default CA_ROTOR3_PZ	0.00

# Motors sim output params
param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104

param set-default SIM_GZ_EC_MIN1 0
param set-default SIM_GZ_EC_MIN2 0
param set-default SIM_GZ_EC_MIN3 0
param set-default SIM_GZ_EC_MIN4 0

param set-default SIM_GZ_EC_MAX1 1500
param set-default SIM_GZ_EC_MAX2 1500
param set-default SIM_GZ_EC_MAX3 1500
param set-default SIM_GZ_EC_MAX4 1500

# Servos (control surfaces) params
param set-default CA_SV_CS_COUNT 7

param set-default CA_SV_CS0_TRIM	0.00
param set-default CA_SV_CS0_TRQ_P	-0.25
param set-default CA_SV_CS0_TRQ_R	0.00
param set-default CA_SV_CS0_TRQ_Y	0.25
param set-default CA_SV_CS0_TYPE	1

param set-default CA_SV_CS1_TRIM	0.00
param set-default CA_SV_CS1_TRQ_P	-0.25
param set-default CA_SV_CS1_TRQ_R	0.00
param set-default CA_SV_CS1_TRQ_Y	0.25
param set-default CA_SV_CS1_TYPE	1

param set-default CA_SV_CS2_TRIM	0.00
param set-default CA_SV_CS2_TRQ_P	-0.25
param set-default CA_SV_CS2_TRQ_R	0.00
param set-default CA_SV_CS2_TRQ_Y	-0.25
param set-default CA_SV_CS2_TYPE	2

param set-default CA_SV_CS3_TRIM	0.00
param set-default CA_SV_CS3_TRQ_P	-0.25
param set-default CA_SV_CS3_TRQ_R	0.00
param set-default CA_SV_CS3_TRQ_Y	-0.25
param set-default CA_SV_CS3_TYPE	2

param set-default CA_SV_CS4_TRIM	0.00
param set-default CA_SV_CS4_TRQ_P	-0.50
param set-default CA_SV_CS4_TRQ_R	0.00
param set-default CA_SV_CS4_TRQ_Y	0.00
param set-default CA_SV_CS4_TYPE	3

param set-default CA_SV_CS5_TRIM	0.00
param set-default CA_SV_CS5_TRQ_P	-0.50
param set-default CA_SV_CS5_TRQ_R	0.00
param set-default CA_SV_CS5_TRQ_Y	0.00
param set-default CA_SV_CS5_TYPE	3

param set-default CA_SV_CS6_TRIM	0.00
param set-default CA_SV_CS6_TRQ_P	0.00
param set-default CA_SV_CS6_TRQ_R	0.25
param set-default CA_SV_CS6_TRQ_Y	0.00
param set-default CA_SV_CS6_TYPE	4

# Servos sim output params
param set-default SIM_GZ_SV_FUNC1	201
param set-default SIM_GZ_SV_FUNC2	202
param set-default SIM_GZ_SV_FUNC3	203
param set-default SIM_GZ_SV_FUNC4	204
param set-default SIM_GZ_SV_FUNC5	205
param set-default SIM_GZ_SV_FUNC6	206
param set-default SIM_GZ_SV_FUNC7	207
param set-default SIM_GZ_SV_MAX1	1000
param set-default SIM_GZ_SV_MAX2	1000
param set-default SIM_GZ_SV_MAX3	1000
param set-default SIM_GZ_SV_MAX4	1000
param set-default SIM_GZ_SV_MAX5	1000
param set-default SIM_GZ_SV_MAX6	1000
param set-default SIM_GZ_SV_MAX7	1000
param set-default SIM_GZ_SV_MIN1	0
param set-default SIM_GZ_SV_MIN2	0
param set-default SIM_GZ_SV_MIN3	0
param set-default SIM_GZ_SV_MIN4	0
param set-default SIM_GZ_SV_MIN5	0
param set-default SIM_GZ_SV_MIN6	0
param set-default SIM_GZ_SV_MIN7	0
param set-default SIM_GZ_SV_MIN8	0

# Disable auto disarm
param set-default COM_DISARM_PRFLT 0
param set-default COM_DISARM_LAND 0

# Board/Sensors orientation
param set-default SENS_BOARD_ROT 6

# Other params
param set-default FD_FAIL_R 70

param set-default FW_P_TC 0.6

param set-default FW_PR_I 0.3
param set-default FW_PR_P 0.5
param set-default FW_PSP_OFF 2
param set-default FW_RR_FF 0.1
param set-default FW_RR_I 0.1
param set-default FW_RR_P 0.2
param set-default FW_YR_FF 0 # make yaw rate controller very weak, only keep default P
param set-default FW_YR_I 0
param set-default FW_THR_TRIM 0.35
param set-default FW_THR_MAX 0.8
param set-default FW_THR_MIN 0.05
param set-default FW_T_CLMB_MAX 6
param set-default FW_T_HRATE_FF 0.5
param set-default FW_T_SINK_MAX 3
param set-default FW_T_SINK_MIN 1.6
param set-default FW_AIRSPD_STALL 10
param set-default FW_AIRSPD_MIN 14
param set-default FW_AIRSPD_TRIM 18
param set-default FW_AIRSPD_MAX 22

param set-default MC_AIRMODE 2
param set-default MAN_ARM_GESTURE 0 # required for yaw airmode
param set-default MC_ROLL_P 3
param set-default MC_PITCH_P 3
param set-default MC_ROLLRATE_P 0.3
param set-default MC_PITCHRATE_P 0.3

param set-default VT_ARSP_TRANS 15
param set-default VT_B_TRANS_DUR 5
param set-default VT_FW_DIFTHR_EN 7
param set-default VT_FW_DIFTHR_S_Y 1
param set-default VT_F_TRANS_DUR 1.5
param set-default VT_TYPE 0

param set-default WV_EN 0

param set-default EKF2_FUSE_BETA 0
